sudo: required
dist: Trusty
script:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install cmake
  - sudo mkdir -p build
  - cd build
  - sudo cmake ..
  - sudo make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake 3.2.2
